sudo: required
services:
  - docker
language: scala
scala:
  - 2.10.6
  - 2.11.7
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
before_install:
  - echo 'DOCKER_OPTS="-D -H tcp://127.0.0.1:2375"' | sudo tee /etc/default/docker
  - sudo service docker restart
script:
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - sbt ++$TRAVIS_SCALA_VERSION "test"
